all: chessboard.py
	@echo "make run for .ppm in file"
	@echo "make imgur to upload to imgur"
run: chessboard.py
	python chessboard.py
imgur: chessboard.py
	python chessboard.py imgur
clean:
	rm *.ppm
	rm *~
